language: C++
dist: bionic

matrix:
  include:
    - name: linux-g++7
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - name: linux-g++8
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - name: linux-g++9
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - name: linux-g++10
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain-gcc.cmake -DCMAKE_VERBOSE_MAKEFILE=true .
  - cmake --build .
  - tests/owi_tests
